//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOBP.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionHistory
    {
        public long ActionId { get; set; }
        public string LicenseTypeId { get; set; }
        public string CurrentFieldLocation { get; set; }
        public string ApplicationId { get; set; }
        public Nullable<short> CurrentStageID { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public string TriggeredBy { get; set; }
        public string TriggeredByRole { get; set; }
        public string MESSAGE { get; set; }
        public string TargetedTo { get; set; }
        public string TargetedToRole { get; set; }
        public Nullable<short> NextStateID { get; set; }
        public string NextFieldLocation { get; set; }
        public string StatusMode { get; set; }
        public string ActionMode { get; set; }
    
        public virtual FieldLocation FieldLocation { get; set; }
        public virtual LicenseType LicenseType { get; set; }
        public virtual ApplicationRequest ApplicationRequest { get; set; }
        public virtual WorkFlowState WorkFlowState { get; set; }
        public virtual WorkFlowState WorkFlowState1 { get; set; }
    }
}
