//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOBP.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseOilStorageTnkFacility
    {
        public int BaseOilStTnkFacId { get; set; }
        public string ApplicationId { get; set; }
        public int NoOfTanks { get; set; }
        public string TypeOfBaseOil { get; set; }
        public int StorageCapacity { get; set; }
        public string SurfaceCondition { get; set; }
        public string LightArrestor { get; set; }
        public string SafetyGauge { get; set; }
        public string LevelIndcSamplePtt { get; set; }
        public string BundWall { get; set; }
        public string DateDtlLstIntegTestOfTnks { get; set; }
    
        public virtual ApplicationRequest ApplicationRequest { get; set; }
    }
}
