//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOBP.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facility
    {
        public int FacilityId { get; set; }
        public string CompanyUserId { get; set; }
        public string FalicityName { get; set; }
        public string LocationAddress { get; set; }
        public Nullable<int> ElpsFacilityId { get; set; }
    }
}
