//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOBP.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Functionality
    {
        public string FuncId { get; set; }
        public string Description { get; set; }
        public string MenuId { get; set; }
        public string Action { get; set; }
        public Nullable<byte> SeqNo { get; set; }
        public string Status { get; set; }
        public string IconName { get; set; }
    }
}
