//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOBP.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectionQualityCtrlProp
    {
        public int InspectionQualityCtrlPropId { get; set; }
        public string ApplicationId { get; set; }
        public string ViscosityTest { get; set; }
        public string ViscosityTestEquip { get; set; }
        public string ViscosityestMthd { get; set; }
        public string ViscosityTestRmks { get; set; }
        public string ViscosityIdx { get; set; }
        public string ViscosityIdxEquip { get; set; }
        public string ViscosityIdxMthd { get; set; }
        public string ViscosityIdxRmks { get; set; }
        public string FlashPoint { get; set; }
        public string FlashPointEquip { get; set; }
        public string FlashPointMthd { get; set; }
        public string FlashPointRmks { get; set; }
        public string PourPoint { get; set; }
        public string PourPointEquip { get; set; }
        public string PourPointMthd { get; set; }
        public string PourPointRmks { get; set; }
        public string TotalBaseNm { get; set; }
        public string TotalBaseNmEquip { get; set; }
        public string TotalBaseNmMthd { get; set; }
        public string TotalBaseNmRmks { get; set; }
        public string TotalAcidNm { get; set; }
        public string TotalAcidNmEquip { get; set; }
        public string TotalAcidNmMthd { get; set; }
        public string TotalAcidNmRmks { get; set; }
        public string Colour { get; set; }
        public string ColourEquip { get; set; }
        public string ColourMthd { get; set; }
        public string ColourRmks { get; set; }
        public string WaterContent { get; set; }
        public string WaterContentEquip { get; set; }
        public string WaterContentMthd { get; set; }
        public string WaterContentRmks { get; set; }
        public string InsolubleContent { get; set; }
        public string InsolubleContentEquip { get; set; }
        public string InsolubleContentMthd { get; set; }
        public string InsolubleContentRmks { get; set; }
        public string AshContent { get; set; }
        public string AshContentEquip { get; set; }
        public string AshContentMthd { get; set; }
        public string AshContentRmks { get; set; }
    
        public virtual ApplicationRequest ApplicationRequest { get; set; }
    }
}
