//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOBP.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntermediateHoldingTank
    {
        public int IntermeHoldingTanksId { get; set; }
        public string ApplicationId { get; set; }
        public int NoOfTanks { get; set; }
        public string TypeOfProduct { get; set; }
        public int StorageCapacity { get; set; }
        public string SurfaceCondition { get; set; }
        public string LevelIndicator { get; set; }
    
        public virtual ApplicationRequest ApplicationRequest { get; set; }
    }
}
