//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOBP.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicenseType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LicenseType()
        {
            this.ActionHistories = new HashSet<ActionHistory>();
            this.Appointments = new HashSet<Appointment>();
            this.PaymentLogs = new HashSet<PaymentLog>();
            this.UserActivities = new HashSet<UserActivity>();
            this.UserActivityHists = new HashSet<UserActivityHist>();
            this.ApplicationRequests = new HashSet<ApplicationRequest>();
        }
    
        public string LicenseTypeId { get; set; }
        public string Description { get; set; }
        public Nullable<int> Tenor { get; set; }
        public Nullable<byte> SequencNo { get; set; }
        public Nullable<int> LicenseSerial { get; set; }
        public Nullable<decimal> ProcessingFees { get; set; }
        public Nullable<int> GracePeriod { get; set; }
        public string Status { get; set; }
        public string Duration { get; set; }
        public Nullable<decimal> Penalty { get; set; }
        public string ShortName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActionHistory> ActionHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentLog> PaymentLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserActivity> UserActivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserActivityHist> UserActivityHists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationRequest> ApplicationRequests { get; set; }
    }
}
