//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOBP.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListOfLubricant
    {
        public int ListOfLubricantsId { get; set; }
        public string ApplicationId { get; set; }
        public string LubricantId { get; set; }
        public string GradeSpecifications { get; set; }
    
        public virtual ApplicationRequest ApplicationRequest { get; set; }
    }
}
