//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOBP.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MistdoData
    {
        public int MistdoAutoId { get; set; }
        public string fullName { get; set; }
        public string phoneNumber { get; set; }
        public string email { get; set; }
        public string certificateNo { get; set; }
        public Nullable<System.DateTime> certificateIssue { get; set; }
        public Nullable<System.DateTime> certificateExpiry { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string ElpsId { get; set; }
        public string HasExpired { get; set; }
        public string mistdoId { get; set; }
    }
}
