//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOBP.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentLog
    {
        public long PaymentId { get; set; }
        public string ApplicationId { get; set; }
        public string ApplicantUserId { get; set; }
        public string LicenseTypeId { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string TransactionID { get; set; }
        public string Description { get; set; }
        public string RRReference { get; set; }
        public string AppReceiptID { get; set; }
        public Nullable<decimal> TxnAmount { get; set; }
        public decimal Arrears { get; set; }
        public string BankCode { get; set; }
        public string Account { get; set; }
        public string TxnMessage { get; set; }
        public string Status { get; set; }
        public Nullable<int> RetryCount { get; set; }
        public Nullable<System.DateTime> LastRetryDate { get; set; }
        public Nullable<decimal> LateRenewalPenalty { get; set; }
        public Nullable<decimal> NonRenewalPenalty { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string AmountTag { get; set; }
        public string PaymentType { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public Nullable<decimal> StatutoryFee { get; set; }
        public Nullable<decimal> ProcessingFee { get; set; }
        public Nullable<decimal> ServiceCharge { get; set; }
    
        public virtual LicenseType LicenseType { get; set; }
        public virtual ApplicationRequest ApplicationRequest { get; set; }
    }
}
