//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOBP.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequiredLicenseDocument
    {
        public int LicenseDocId { get; set; }
        public string LicenseTypeId { get; set; }
        public string ApplicationTypeId { get; set; }
        public int TypeID { get; set; }
        public string Description { get; set; }
        public Nullable<byte> SeqNo { get; set; }
        public string IsBaseTran { get; set; }
        public string IsMandatory { get; set; }
        public string IsLicenseDoc { get; set; }
        public string Status { get; set; }
    }
}
