//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOBP.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestFieldMapping
    {
        public int RequestFieldMappId { get; set; }
        public string StateCode { get; set; }
        public string ApplicationType { get; set; }
        public string FieldLocationID { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string Status { get; set; }
    
        public virtual FieldLocation FieldLocation { get; set; }
        public virtual StateMasterList StateMasterList { get; set; }
    }
}
