//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOBP.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubmittedDocument
    {
        public int SubmitedDocId { get; set; }
        public string ApplicationID { get; set; }
        public int FileId { get; set; }
        public int DocId { get; set; }
        public string DocSource { get; set; }
        public string BaseorTrans { get; set; }
        public string DocName { get; set; }
    }
}
