//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOBP.DbEntities
{
    using System;
    using System.Collections.Generic;
    [Serializable]

    public partial class UserActivityHist
    {
        public int ActivityHistId { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public string UserId { get; set; }
        public string ApplicationId { get; set; }
        public string LicenseTypeId { get; set; }
        public Nullable<System.DateTime> ActivityOn { get; set; }
        public Nullable<short> CurrentStageID { get; set; }
    
        public virtual LicenseType LicenseType { get; set; }
        public virtual UserActivity UserActivity { get; set; }
    }
}
