//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOBP.DbEntities
{
    using System;
    using System.Collections.Generic;
    [Serializable]

    public partial class UserLogin
    {
        public long LoginPk { get; set; }
        public string UserId { get; set; }
        public string UserType { get; set; }
        public string Browser { get; set; }
        public string Client { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public string Status { get; set; }
        public string LoginMessage { get; set; }
    }
}
