//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOBP.DbEntities
{
    using System;
    using System.Collections.Generic;
    [Serializable]

    public partial class UserMaster
    {
        public string UserId { get; set; }
        public string UserType { get; set; }
        public string ElpsId { get; set; }
        public string CACNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserLocation { get; set; }
        public string UserRoles { get; set; }
        public string UserDesignation { get; set; }
        public byte[] UserImage { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<int> LoginCount { get; set; }
        public string NotificationAllowed { get; set; }
        public string LastComment { get; set; }
        public Nullable<int> SignatureID { get; set; }
        public string SignatureImage { get; set; }
        public int UserMasterId { get; set; }
    
        public virtual FieldLocation FieldLocation { get; set; }
    }
}
