//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOBP.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkFlowNavigation
    {
        public int WorkFlowId { get; set; }
        public string LicenseTypeId { get; set; }
        public string FieldLocationApply { get; set; }
        public string ApplicationType { get; set; }
        public string Action { get; set; }
        public string ActionRole { get; set; }
        public short CurrentStageID { get; set; }
        public short NextStateID { get; set; }
        public string TargetRole { get; set; }
        public string NotifyAction { get; set; }
        public string NextActionRole { get; set; }
    }
}
