//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOBP.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZoneFieldMapping
    {
        public int ZoneFieldMappId { get; set; }
        public string ZoneFieldID { get; set; }
        public string FieldLocationID { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string Status { get; set; }
    
        public virtual FieldLocation FieldLocation { get; set; }
        public virtual FieldLocation FieldLocation1 { get; set; }
    }
}
