CREATE TABLE [dbo].[ApplicationRequest] (
    [LicenseTypeId]                         VARCHAR (10)    NULL,
    [ApplicationTypeId]                     VARCHAR (10)    NULL,
    [ApplicationId]                         VARCHAR (30)    NOT NULL,
    [ApplicantUserId]                       VARCHAR (50)    NULL,
    [ApplicantName]                         VARCHAR (350)   NULL,
    [RegisteredAddress]                     VARCHAR (MAX)   NULL,
    [SiteLocationAddress]                   VARCHAR (MAX)   NULL,
    [StateCode]                             NVARCHAR (3)    NULL,
    [LgaCode]                               NVARCHAR (6)    NULL,
    [GPSCordinates]                         VARCHAR (200)   NULL,
    [LandSize]                              NVARCHAR (50)   NULL,
    [BeaconLocations]                       NVARCHAR (MAX)  NULL,
    [LandTopology]                          NVARCHAR (150)  NULL,
    [NatureOfArea]                          NVARCHAR (150)  NULL,
    [AdjoiningProperties]                   NVARCHAR (MAX)  NULL,
    [AccessRoadToFromSite]                  NVARCHAR (MAX)  NULL,
    [AnyEquipmentOnSite]                    NVARCHAR (MAX)  NULL,
    [RelationshipWithPipelineRightOfWay]    NVARCHAR (MAX)  NULL,
    [RelationshipWithStreams]               NVARCHAR (MAX)  NULL,
    [RelationshipWithPHCNTensionLines]      NVARCHAR (MAX)  NULL,
    [RelationshipWithRailwayLine]           NVARCHAR (MAX)  NULL,
    [RelationshipWithSensitiveInstitutions] NVARCHAR (MAX)  NULL,
    [NoReasonText]                          NVARCHAR (MAX)  NULL,
    [GeoLocation]                           NVARCHAR (MAX)  NULL,
    [PlantTypes]                            NVARCHAR (150)  NULL,
    [ProdBaseOilRequirement]                NVARCHAR (MAX)  NULL,
    [LubricantProdByCompany]                NVARCHAR (MAX)  NULL,
    [AnnualCumuBaseOilRequirementCapacity]  NVARCHAR (150)  NULL,
    [AnnualProductionProjectionCapacity]    NVARCHAR (150)  NULL,
    [ListOfPropTrainingforStaff]            NVARCHAR (MAX)  NULL,
    [PreventiveAnnualMaintPrgmPlant]        NVARCHAR (MAX)  NULL,
    [AdditionalInfo]                        NVARCHAR (MAX)  NULL,
    [CurrentStageID]                        SMALLINT        NULL,
    [CurrentAssignedUser]                   VARCHAR (150)   NULL,
    [CurrentOfficeLocation]                 VARCHAR (3)     NULL,
    [LicenseIssuedDate]                     DATETIME        NULL,
    [LicenseExpiryDate]                     DATETIME        NULL,
    [LicenseReference]                      VARCHAR (30)    NULL,
    [LinkedReference]                       VARCHAR (50)    NULL,
    [AddedDate]                             DATETIME        NULL,
    [ModifiedDate]                          DATETIME        NULL,
    [IsLegacy]                              VARCHAR (10)    NULL,
    [Status]                                VARCHAR (10)    NULL,
    [StorageCapacity]                       VARCHAR (20)    NULL,
    [NetAmount]                             DECIMAL (20, 2) NULL,
    [SignatureID]                           INT             NULL,
    [FacilityId]                            INT             NULL,
    [PermitElpsId]                          INT             NULL,
    [PrintedStatus]                         VARCHAR (15)    NULL,
    [ApplicationCategory]                   VARCHAR (100)   NULL,
    [Quarter]                               INT             NULL,
    [PLW_PRW_Name]                          VARCHAR (200)   NULL,
    [PLW_PRW_Address]                       VARCHAR (MAX)   NULL,
    [ApplicationRequestId]                  INT             IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK__Applicat__C93A4C99EDB181DA] PRIMARY KEY CLUSTERED ([ApplicationId] ASC),
    CONSTRAINT [FK_ApplicationRequest_FieldLocation] FOREIGN KEY ([CurrentOfficeLocation]) REFERENCES [dbo].[FieldLocation] ([FieldLocationID]),
    CONSTRAINT [FK_ApplicationRequest_StateMasterList] FOREIGN KEY ([StateCode]) REFERENCES [dbo].[StateMasterList] ([StateCode]),
    CONSTRAINT [FK_ApplicationRequest_WorkFlowState] FOREIGN KEY ([CurrentStageID]) REFERENCES [dbo].[WorkFlowState] ([StateID]),
    CONSTRAINT [FK_APPLicenseTypeCode] FOREIGN KEY ([LicenseTypeId]) REFERENCES [dbo].[LicenseType] ([LicenseTypeId]),
    CONSTRAINT [FK_AppRequest_LgaCode] FOREIGN KEY ([LgaCode]) REFERENCES [dbo].[LgaMasterList] ([LgaCode])
);


GO
ALTER TABLE [dbo].[ApplicationRequest] NOCHECK CONSTRAINT [FK_APPLicenseTypeCode];

