CREATE TABLE [dbo].[InspectionDetailSummaryRpt] (
    [InspectionDetailSummReptId]              INT           IDENTITY (1, 1) NOT NULL,
    [ApplicationId]                           VARCHAR (30)  NOT NULL,
    [TypeOfPlantId]                           VARCHAR (3)   NOT NULL,
    [AnnualEstBaseOilDmd]                     INT           NOT NULL,
    [AnnualEstAdditiveDmd]                    INT           NOT NULL,
    [SourceOfBaseOil]                         VARCHAR (500) NOT NULL,
    [SourceOfAdditives]                       VARCHAR (500) NOT NULL,
    [ModeofPkgLubeCanSize]                    INT           NOT NULL,
    [ModeofPkgLubeDrumSize]                   INT           NOT NULL,
    [ModeofPkgLubeBulkDest]                   VARCHAR (500) NOT NULL,
    [NbrFillingHeadCan]                       INT           NOT NULL,
    [NbrFillingHeadCanOprtnl]                 INT           NOT NULL,
    [NbrFillingHeadDrum]                      INT           NOT NULL,
    [NbrFillingHeadDrumOprtnl]                INT           NOT NULL,
    [NbrFillingHeadBulk]                      INT           NOT NULL,
    [NbrFillingHeadBulkOprtnl]                INT           NOT NULL,
    [AnalDesignProdCapVsActlProd]             VARCHAR (500) NOT NULL,
    [HasLabForQualityControlAssurance]        VARCHAR (5)   NOT NULL,
    [HasLabQualityControlProfessional]        VARCHAR (5)   NOT NULL,
    [IstheLaboraryEquippedForLubeProp]        VARCHAR (5)   NOT NULL,
    [HasFunctionalClinicOrFAidBox]            VARCHAR (250) NOT NULL,
    [HasEmergencyResponsePlan]                VARCHAR (250) NOT NULL,
    [GeneralHouseKeepingofPlantPremises]      VARCHAR (MAX) NOT NULL,
    [TreatmentPriorToEffluentDisposal]        VARCHAR (MAX) NOT NULL,
    [NameDetailThirdPartyLabEffluentAnalysis] VARCHAR (MAX) NOT NULL,
    [GeneralImpressionsFindings]              VARCHAR (MAX) NOT NULL,
    [Recommendations]                         VARCHAR (MAX) NOT NULL,
    [DateOfInspection]                        DATETIME      NOT NULL,
    [NameOfDPROfficers]                       VARCHAR (MAX) NOT NULL,
    [NameOfPlantRepresentative]               VARCHAR (500) NOT NULL,
    CONSTRAINT [PK__Inspecti__A7B9797B70AACE9D] PRIMARY KEY CLUSTERED ([InspectionDetailSummReptId] ASC),
    CONSTRAINT [FK_InspectnDtlSummaryRpt_ApplicationId] FOREIGN KEY ([ApplicationId]) REFERENCES [dbo].[ApplicationRequest] ([ApplicationId]),
    CONSTRAINT [FK_InspectnDtlSummaryRpt_TypeOfPlantId] FOREIGN KEY ([TypeOfPlantId]) REFERENCES [dbo].[TypeOfPlantLookUp] ([TypeOfPlantId])
);

