CREATE TABLE [dbo].[InspectionQualityCtrlProp] (
    [InspectionQualityCtrlPropId] INT           IDENTITY (1, 1) NOT NULL,
    [ApplicationId]               VARCHAR (30)  NOT NULL,
    [ViscosityTest]               VARCHAR (5)   NOT NULL,
    [ViscosityTestEquip]          VARCHAR (MAX) NOT NULL,
    [ViscosityestMthd]            VARCHAR (MAX) NOT NULL,
    [ViscosityTestRmks]           VARCHAR (MAX) NOT NULL,
    [ViscosityIdx]                VARCHAR (5)   NOT NULL,
    [ViscosityIdxEquip]           VARCHAR (MAX) NOT NULL,
    [ViscosityIdxMthd]            VARCHAR (MAX) NOT NULL,
    [ViscosityIdxRmks]            VARCHAR (MAX) NOT NULL,
    [FlashPoint]                  VARCHAR (5)   NOT NULL,
    [FlashPointEquip]             VARCHAR (MAX) NOT NULL,
    [FlashPointMthd]              VARCHAR (MAX) NOT NULL,
    [FlashPointRmks]              VARCHAR (MAX) NOT NULL,
    [PourPoint]                   VARCHAR (5)   NOT NULL,
    [PourPointEquip]              VARCHAR (MAX) NOT NULL,
    [PourPointMthd]               VARCHAR (MAX) NOT NULL,
    [PourPointRmks]               VARCHAR (MAX) NOT NULL,
    [TotalBaseNm]                 VARCHAR (5)   NOT NULL,
    [TotalBaseNmEquip]            VARCHAR (MAX) NOT NULL,
    [TotalBaseNmMthd]             VARCHAR (MAX) NOT NULL,
    [TotalBaseNmRmks]             VARCHAR (MAX) NOT NULL,
    [TotalAcidNm]                 VARCHAR (5)   NOT NULL,
    [TotalAcidNmEquip]            VARCHAR (MAX) NOT NULL,
    [TotalAcidNmMthd]             VARCHAR (MAX) NOT NULL,
    [TotalAcidNmRmks]             VARCHAR (MAX) NOT NULL,
    [Colour]                      VARCHAR (5)   NOT NULL,
    [ColourEquip]                 VARCHAR (MAX) NOT NULL,
    [ColourMthd]                  VARCHAR (MAX) NOT NULL,
    [ColourRmks]                  VARCHAR (MAX) NOT NULL,
    [WaterContent]                VARCHAR (5)   NOT NULL,
    [WaterContentEquip]           VARCHAR (MAX) NOT NULL,
    [WaterContentMthd]            VARCHAR (MAX) NOT NULL,
    [WaterContentRmks]            VARCHAR (MAX) NOT NULL,
    [InsolubleContent]            VARCHAR (5)   NOT NULL,
    [InsolubleContentEquip]       VARCHAR (MAX) NOT NULL,
    [InsolubleContentMthd]        VARCHAR (MAX) NOT NULL,
    [InsolubleContentRmks]        VARCHAR (MAX) NOT NULL,
    [AshContent]                  VARCHAR (5)   NOT NULL,
    [AshContentEquip]             VARCHAR (MAX) NOT NULL,
    [AshContentMthd]              VARCHAR (MAX) NOT NULL,
    [AshContentRmks]              VARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK__Inspecti__BDC77AFA630EEBEF] PRIMARY KEY CLUSTERED ([InspectionQualityCtrlPropId] ASC),
    CONSTRAINT [FK_InspectionQualityCtrlProp_ApplicationId] FOREIGN KEY ([ApplicationId]) REFERENCES [dbo].[ApplicationRequest] ([ApplicationId])
);

